[package]
name = "handranker"
version = "0.1.0"
authors = ["bhavesh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixedbitset = "0.3.0"